initialize headers to {} if we need to copy some.
Not sure if this is a bug in underscore, but without this I got: 

najax/node_modules/underscore/underscore.js:822
          obj[prop] = source[prop];
                    ^
TypeError: Cannot set property '...' of undefined